name: SIGPwny
author: SIGPwny
description: Undergrad Infosec @ UIUC
github: //www.github.com/sigpwny
facebook: //www.facebook.com/groups/439995656109426
twitter: //twitter.com/SIGPwny
email: sigpwny@gmail.com

highlighter: rouge
markdown: kramdown
redcarpet:
  extensions: ["tables"]

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

collections: 
  meetings:
    output: true
    permalink: /:collection/:path
