meeting_time: "18:00-19:00 CDT"
meeting_location: "Zoom (join Discord to get link)"

title: SIGPwny
twitter_username: SIGPwny
github_username: sigpwny
facebook_link: https://www.facebook.com/groups/439995656109426
discord_link: https://discord.gg/cWcZ6a9

collections:
  meetings:
    output: true
    permalink: /:collection/:path
  events:
    output: true
    permalink: /:collection/:path
  redirects:
    output: true
    permalink: /:path
  writeups:
    output: true
    permalink: /:collection/:path

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

sass:
  style: compressed
